### ISSUE TITLE
Multiple dex files define error

### ISSUE THREAD

**Issue by smkamranqadri** [dpa99c/cordova-android-support-gradle-release#1]
After install this plugin, got this error.

com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException:
        java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define
        Lcom/google/android/gms/iid/zzc;

**Comment by smkamranqadri** [comment]
project.properties

target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:24.1.1+
cordova.system.library.2=com.facebook.android:facebook-android-sdk:4.14.+
cordova.system.library.3=com.google.android.gms:play-services-maps:11.+
cordova.system.library.4=com.google.android.gms:play-services-location:11.+
cordova.gradle.include.1=cordova-plugin-mauron85-background-geolocation/driver-logtofile.gradle
cordova.system.library.5=com.google.android.gms:play-services-location:+
cordova.system.library.6=com.android.support:support-v4:+
cordova.system.library.7=com.android.support:support-v4:24.1.1+
cordova.system.library.8=com.android.support:support-v4:25.+
cordova.system.library.9=com.android.support:appcompat-v7:25.+
cordova.gradle.include.2=phonegap-plugin-push/driver-push.gradle
cordova.system.library.10=com.android.support:support-v13:23+
cordova.system.library.11=com.google.android.gms:play-services-gcm:9.8+
cordova.system.library.12=me.leolin:ShortcutBadger:1.1.4@aar
cordova.gradle.include.3=cordova-android-support-gradle-release/driver-cordova-android-support-gradle-release.gradle

**Comment by dpa99c** [comment]
Did you remove and re-add the android platform to rebuild the Gradle config after adding this plugin to the project?

**Comment by smkamranqadri** [comment]
Nope, let me try.

thanks for prompt response.

**Comment by dpa99c** [comment]
Closed due to no response from OP.

**Comment by smkamranqadri** [comment]
sorry for not responding, actually it works, have to delete plugins and platforms both.

**Comment by yesprasoon** [comment]
I am getting same error.
1. I am using this plugin because I was getting `Error:Execution failed for task ':processDebugManifest'. > Manifest merger failed` in "phonegap-plugin-barcodescanner" plugin
2. Once I add this plugin I get the same error as Original Poster posted.
3. I remove android platform and add again - again same error.
4. I remove plugin - I get error as stated in 1.

**Comment by smkamranqadri** [comment]
Please try again by first removing all three folders. (node_modules, platforms and plugins)
