### ISSUE TITLE
Error: Cannot find module 'xml2js'

### ISSUE THREAD

**Issue by 0pt1m1z3r** [dpa99c/cordova-android-support-gradle-release#10]
Last version 1.1.3
cordova 6.5.0
Run `cordova prepare` with empty platforms and plugins.

`Failed to install 'cordova-android-support-gradle-release':Error: Cannot find module 'xml2js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../plugins/cordova-android-support-gradle-release/scripts/after-prepare.js:3:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
Failed to restore plugin "cordova-android-support-gradle-release" from config.xml. You might need to try adding it again. Error: Error: Cannot find module 'xml2js'`

**Comment by dpa99c** [comment]
The plugin needs to be installed using `cordova-fetch` which installs the plugin's [npm dependencies](https://github.com/dpa99c/cordova-android-support-gradle-release/blob/master/package.json#L8).

`cordova@7` does this by default, but for `cordova@6` you'll need to install with the `--fetch` option, i.e.

    cordova plugin add cordova-android-support-gradle-release --fetch

Or just update to `cordova@7`

**Comment by 0pt1m1z3r** [comment]
@dpa99c thank you!

I try `cordova@7` but I have one problem, plugins installing take a lot of time. I have 21 plugins. With `cordova@6` they install for 1 minute. With `cordova@7` more than 30 minutes. This is critical for me and I don't know how to solve this.
Did you have the same problem?

**Comment by dpa99c** [comment]
`cordova@7` is slower for me too. 

`cordova@7` installs each plugin twice: one copy to `node_modules/` using `npm install` (the new `cordova-fetch` mechanism) and one to `plugins/` (where by `cordova@6` and below installs plugins using the legacy `git clone` mechanism).

I assume `cordova@8` will drop the old `git clone` mechanism and just use `npm install` to install the plugins.

`cordova@7` supports the `--nofetch` option which uses only the legacy `git clone` mechanism to install plugins, but that will not satisfy the node dependencies of plugins such as this one.
