### ISSUE TITLE
Cordova compile android OK but not cordova run android

### ISSUE THREAD

**Issue by pom421** [dpa99c/cordova-android-support-gradle-release#12]
One other problem today ;)

With  Cordova CLI 7.1.1, when i type "cordova run android", i obtain :

```
Error: cordova-android-support-gradle-release: Failed to load dependencies. If using cordova@6 CLI, ensure this plugin is installed with the --fetch option: Cannot find module 'xml2js'
```
When i use "cordova compile android", the apk is generated without issue.

**Comment by dpa99c** [comment]
The plugin [includes xml2js](https://github.com/dpa99c/cordova-android-support-gradle-release/blob/master/package.json#L8) as a dependency in its package.json. Therefore it relies on being installed by the `cordova-fetch` mechanism which will run `npm install` in the context of the package.json to install the module into `node_modules/`.
If the `node_modules/` directory was removed after plugin installation, this would also cause this error.

**Comment by dpa99c** [comment]
Can this be closed?

**Comment by pom421** [comment]
I have downgraded my CLI, I'm using now 7.0.1 and it's OK.
You can close it, I'll reopen it later if i face the same issue again.
