### ISSUE TITLE
Problem file location cordova-android-support-gradle-release/properties.gradle

### ISSUE THREAD

**Issue by pom421** [dpa99c/cordova-android-support-gradle-release#13]
I want to upgrade to the latest cordova android and plugin.
I have a problem with the cordova-android-support-gradle-release.

My environment : 

- cordova cli 8.0.0
- cordova android engine 7.0.0
- plugins 

```
"com.bez4pieci.cookies": "~0.0.1",
"cordova-android": "^7.0.0",
"cordova-android-support-gradle-release": "^1.1.5",
"cordova-browser": "^4.1.0",
"cordova-ios": "^4.5.3",
"cordova-open-native-settings": "^1.4.1",
"cordova-plugin-app-version": "^0.1.9",
"cordova-plugin-clipboard2": "^0.1.0",
"cordova-plugin-compat": "^1.2.0",
"cordova-plugin-config-ios": "0.0.1",
"cordova-plugin-device": "^2.0.1",
"cordova-plugin-dialogs": "^2.0.1",
"cordova-plugin-file": "^5.0.0",
"cordova-plugin-file-opener2": "^2.0.19",
"cordova-plugin-file-transfer": "^1.7.0",
"cordova-plugin-inappbrowser": "^2.0.1",
"cordova-plugin-network-information": "^2.0.1",
"cordova-plugin-statusbar": "^2.4.1",
"cordova-plugin-whitelist": "^1.3.3",
"cordova-plugin-x-socialsharing": "^5.2.1",
"cordova.plugins.diagnostic": "^3.9.1",
"es6-promise-plugin": "^4.1.0",
"phonegap-plugin-barcodescanner": "^7.0.1"
```

### Output of “cordova compile android"

```
ANDROID_HOME=/Users/pomauguet/android-sdks
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home
Reading build config file: /Users/pomauguet/workspace/impots/trunk/impots-gouv/build.json
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: compileSdkVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:456)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:590)
	at com.android.build.gradle.BasePlugin.lambda$null$3(BasePlugin.java:555)


FAILURE: Build failed with an exception.

* Where:
Script '/Users/pomauguet/workspace/impots/trunk/impots-gouv/platforms/android/cordova-android-support-gradle-release/android-cordova-android-support-gradle-release.gradle' line: 11

* What went wrong:
A problem occurred evaluating script.
> Could not read script '/Users/pomauguet/workspace/impots/trunk/impots-gouv/platforms/android/app/cordova-android-support-gradle-release/properties.gradle' as it does not exist.


BUILD FAILED in 1s
(node:9783) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /Users/pomauguet/workspace/impots/trunk/impots-gouv/platforms/android/gradlew: Command failed with exit code 1 Error output:
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: compileSdkVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:456)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:590)

```

I suppose this problem is in relation with the decision of reorganizing the source code since Cordova Android 7.0.0 (https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html).

After test with Android engine 6.4.0, everything work fine. So this is indeed a problem with 7.0.0.

**Comment by dpa99c** [comment]
That commit should add compatibility for the `cordova-android@7` project structure, but maintains backward-compatibility for the `cordova-android@6`. Published to npm as `cordova-android-support-gradle-release@1.2.0` so give it a try.

**Comment by pom421** [comment]
It works. Thanks! 👍

**Comment by lovelyelfpop** [comment]
for cordova-android@7.0.0, `ANDROID_SUPPORT_VERSION` inside `platforms/android/app/cordova-android-support-gradle-release/properties.gradle` is still `26.+`.

**Comment by alonetech** [comment]
Same problem 

cordova -v  8.0.0
ionic 3
i just update cordova-android from 6.3.0 to 7.0.0 and remove platform and then add it again.
getting these error while build the app.

cordova-android-play-services-gradle-release: Android platform: cordova-android@7
cordova-android-play-services-gradle-release: No custom version found in config.xml - using plugin default
(node:5432) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Invalid data, chunk must be a string or buffer, not object

**Comment by martinsotirov** [comment]
I had the same problem and fixed it by manually creating the folder `platforms/android/app/cordova-android-support-gradle-release` and copying `platforms/android/app/build.gradle` to `platforms/android/app/cordova-android-support-gradle-release/properties.gradle`.

**Comment by OlatunjiGab** [comment]
The problem disappeared after following martinsotirov  idea but got this error:
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_181
Cannot read property 'length' of undefined
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd build android exited with exit code 1.
Any help to this?
