### ISSUE TITLE
Failed to create component for 'dialog' reason: java.awt.HeadlessException

### ISSUE THREAD

**Issue by 0pt1m1z3r** [dpa99c/cordova-android-support-gradle-release#17]
Cordova 8.
Build android with `--release`.

```FAILURE: Build failed with an exception.

* Where:
Script '/Users/ezheg/servicewhale/sw-mobile/platforms/android/CordovaLib/cordova.gradle' line: 147

* What went wrong:
Failed to create component for 'dialog' reason: java.awt.HeadlessException
> java.awt.HeadlessException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
(node:80324) UnhandledPromiseRejectionWarning: Error: /Users/ezheg/servicewhale/sw-mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
```

cordova.gradle
```def doPromptForPassword(msg) {
    if (System.console() == null) {
        def ret = null
        new SwingBuilder().edt {
147:        dialog(modal: true, title: 'Enter password', alwaysOnTop: true, resizable: false, locationRelativeTo: null, pack: true, show: true) {
                vbox {
                    label(text: msg)
                    def input = passwordField()
                    button(defaultButton: true, text: 'OK', actionPerformed: {
                        ret = input.password;
                        dispose();
                    })
                }
            }
        }
        if (!ret) {
            throw new GradleException('User canceled build')
        }
        return new String(ret)
    } else {
        return System.console().readPassword('\n' + msg);
    }
}
```

**Comment by dpa99c** [comment]
This is not sufficient information to indicate this plugin as the cause of the build failure. 

You haven't completed the issue template, so details of your build environment are not present. Please complete the issue template, giving a full comprehensive description of the issue.

Also please try building a test Cordova project containing only this plugin to confirm the issue is not caused by another component. If the build fails, please provide the full console log.

If the above information is not provided, the issue will be deemed invalid and closed.

**Comment by 0pt1m1z3r** [comment]
Sorry, it's not the plugin's fault. I found discussion of this problem: https://issues.apache.org/jira/browse/CB-13684#2826

**Comment by Poyoman39** [comment]
You have to specify --storePassword and --password in the release command line.

Here is the solution i found to keep the prompt : 

```
read -p "Please enter store password:" password && cordova build android --release -- --storePassword=$password 
```
Works fine and avoid storing password in configuration files

**Comment by vldmrrr** [comment]
@Poyoman39: make sure you understand that with this approach you password is visible to anyone who can access list of you processes while your build task is running

**Comment by Poyoman39** [comment]
You right ! 👍  I didn't found a password alternative :/

**Comment by vldmrrr** [comment]
Well, here is something a bit more secure that I've just setup for myself:
```
#!/usr/bin/bash

trap interrupted INT
function interrupted() {
    rm -f platforms/android/release.properties
}

stty -echo
read -p "Store Password: " spassw; echo
read -p "Key Password: " kpassw; echo
stty echo

cat << EOT > platforms/android/release.properties
storeFile=../../local/my.keystore
storePassword=$spassw
keyAlias=release_key
keyPassword=$kpassw
EOT

export ORG_GRADLE_PROJECT_cdvReleaseSigningPropertiesFile=../release.properties 
cordova build --release android
rm platforms/android/release.properties
```

**Comment by ssz360** [comment]
For Windows, I've created a `build.cmd` file:
(replace the keystore path and alias)
`@echo off && set /P spassw="Store Password: " && set /P kpassw="Key Password: " && cordova build android --release -- --keystore=../../local/my.keystore --storePassword=%spassw% --alias=tmpalias --password=%kpassw%
`

**Comment by reynaldots** [comment]
My build.cmd for windows:

`@echo off && set spassw=%1 && set xalias=%2 && ionic cordova build android --prod --aot            --minifyjs --minifycss --optimizejs --release && jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore ..\Android\key.keystore platforms\android\app\build\outputs\apk\release\app-release-unsigned.apk %xalias% -storepass %spassw% && zipalign -f -v 4 platforms\android\app\build\outputs\apk\release\app-release-unsigned.apk ..\android\AppProducao.apk`

On Prompt inside ionic folder and keystore in another parent folder:
`build.cmd xpss xals`

With this batch, is created apk unsigned, sign and align, saving de final apk on another folder

Thanks @ssz360, your code helped me to create this version.

**Comment by wihangaD** [comment]
> For Windows, I've created a `build.cmd` file:
> (replace the keystore path and alias)
> `@echo off && set /P spassw="Store Password: " && set /P kpassw="Key Password: " && cordova build android --release -- --keystore=../../local/my.keystore --storePassword=%spassw% --alias=tmpalias --password=%kpassw% `

**Comment by wihangaD** [comment]
this works
