### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by zyhou** [dpa99c/cordova-android-support-gradle-release#18]
**I'm submitting a ...**:
- [X] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

I have a first error in my build ` com.android.ide.common.process.ProcessException: Failed to execute aapt`, look above about error console.
<details>
<summary>Error build dialogCornerRadius</summary>
:processReleaseResources/home/max/app/1859Cloud/efn-app/cordova-build/platforms/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7:41-73: AAPT: No resource found that matches the given name (at 'dialogCornerRadius' with value '?android:attr/dialogCornerRadius').    Failed to generate resource table for split ''
/home/max/app/1859Cloud/efn-app/cordova-build/platforms/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: Error: No resource found that matches the given name (at 'dialogCornerRadius' with value '?android:attr/dialogCornerRadius').

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 21.335 secs
Error: my-path/efn-app/cordova-build/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
my-pathcordova-build/platforms/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7:41-73: AAPT: No resource found that matches the given name (at 'dialogCornerRadius' with value '?android:attr/dialogCornerRadius').    Failed to generate resource table for split ''
my-path/cordova-build/platforms/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: Error: No resource found that matches the given name (at 'dialogCornerRadius' with value '?android:attr/dialogCornerRadius').

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
</details><br /><br />

So, I decide to install this plugin, look `Related code` section, but I have another error look `Console output` section

**Environment information**

- Cordova CLI version 
	- `6.5.0`
- Cordova platform version
	- `android 6.3.0`
- Plugins & versions installed in project (including this plugin)
    - `com.batch.cordova 1.7.4 "Batch"`
    - `cordova-android-support-gradle-release 1.2.1 "cordova-android-support-gradle-release"`
    - `cordova-custom-config 5.0.2 "cordova-custom-config"`
    - `cordova-plugin-background-fetch 5.3.0 "CDVBackgroundFetch"`
    - `cordova-plugin-disable-bitcode 1.3.2 "DisableBitcode"`
    - `cordova-plugin-file 6.0.1 "File"`
    - `cordova-plugin-file-transfer 1.6.3 "File Transfer"`
    - `cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"`
    - `cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"`
    - `cordova-plugin-network-information 1.3.4 "Network Information"`
    - `cordova-plugin-splashscreen 4.0.3 "Splashscreen"`
    - `cordova-plugin-statusbar 2.2.3 "StatusBar"`
    - `cordova-plugin-whitelist 1.3.3 "Whitelist"`
    - `cordova-universal-links-plugin 1.2.1 "Universal Links Plugin`

_Android build issue:_	
- Node JS version
    - `8.10.0`
- Gradle version
	- `I have 3.3 and 4.1 directory`
- Target Android SDK version
	- `<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="26"/>l`

**Related code:**

In config.xml :
```
    <plugin name="cordova-android-support-gradle-release" source="npm" spec="~1.2.0">
        <variable name="ANDROID_SUPPORT_VERSION" value="26.+" />
    </plugin>
```

**Console output**

<details>
<summary>Error build</summary>
:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms.license'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.036 secs
Error: my-path/cordova-build/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms.license'
</details>

**Comment by dpa99c** [comment]
> Error: more than one library with package name 'com.google.android.gms.license'

This error is caused by a mismatch of Google Play Services libraries, rather than Android Support library which this plugin relates to. You can find many issues on StackOverflow relating to this such as [this one](https://stackoverflow.com/questions/49398026/error-more-than-one-library-with-package-name-com-google-android-gms-license).

You need to align the Google Play Services library versions as this plugin does for Android Support Library. You can do this using my related plugin [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release) as [outlined here](https://stackoverflow.com/a/49431381/777265)

**Comment by avinashlb** [comment]
(https://github.com/dpa99c/cordova-android-support-gradle-release/issues/18)
