### ISSUE TITLE
build failed if no plugin is injected via config.xml

### ISSUE THREAD

**Issue by iwan-uschka** [dpa99c/cordova-android-support-gradle-release#2]
If i don't have any plugin which needs to be configured in the config.xml, `cordova-android-support-gradle-release` produces an error

```
Error: Cannot read property 'length' of undefined
```

Please have a look at `scripts/before-prepare.js#15` of the current release version where `plugins` also can be undefined.

thx

**Comment by Habared** [comment]
+1

**Comment by dpa99c** [comment]
Fix published in `@1.1.1`

**Comment by 0pt1m1z3r** [comment]
@dpa99c this problem is still reproduced with latest version when I run `cordova prepare` with empty platforms and plugins.
I think problem in `if (!plugin.variable.length) {`.
With `<variable name="ANDROID_SUPPORT_VERSION" value="25.+" />` not reproduced.

cordova 7.1.0

**Comment by dpa99c** [comment]
@0pt1m1z3r Should be properly fixed in v1.1.3

**Comment by marcus13371337** [comment]
Still have this error
