### ISSUE TITLE
A problem occurred configuring root project 'android'. > Failed to find Platform SDK with path: platforms;android-25

### ISSUE THREAD

**Issue by moludr** [dpa99c/cordova-android-support-gradle-release#20]
<npm WARN pouchdb-adapter-utils@6.0.7 requires a peer of pouchdb-core@6.0.7 but none was installed.
npm WARN pouchdb-adapter-websql-core@6.0.7 requires a peer of pouchdb-core@6.0.7 but none was installed.
npm WARN profitguru@1.1.0 No repository field.
npm WARN profitguru@1.1.0 No license field.
cordova run android
Running command: /home/diwakar/ws/profitGuruMAPP/hooks/after_prepare/010_add_platform_class.js /home/diwakar/ws/profitGuruMAPP
ANDROID_HOME=/usr/lib/android-sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Subproject Path: CordovaLib
Starting a Gradle Daemon (subsequent builds will be faster)
null
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_8fawcafcgpbn8kv385emc80ce.run(/home/diwakar/ws/profitGuruMAPP/platforms/android/build.gradle:139)
org.xwalk:xwalk_core_library:23+
java.net.UnknownHostException: dl.google.com
Failed to connect to host: https://dl.google.com/android/repository/addons_list-3.xml
Failed to connect to host: https://dl.google.com/android/repository/addons_list-2.xml
Failed to connect to host: https://dl.google.com/android/repository/addons_list-1.xml
Failed to download any source lists!

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Failed to find Platform SDK with path: platforms;android-25

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 38.521 secs
(node:14798) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /home/diwakar/ws/profitGuruMAPP/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

# Feature request

# Documentation issue

**Comment by dpa99c** [comment]
This build error has nothing to do with this plugin. It is caused because Gradle could not reach the Google servers.
