### ISSUE TITLE
Upgrading android platform to 7.0.1 version can not be finished

### ISSUE THREAD

**Issue by abdurahmanadilovic** [dpa99c/cordova-android-support-gradle-release#24]
**I'm submitting:**

- [x] bug report

# Bug report

**Current behavior:**

I have a cordova project, I want to upgrade android platform to latest version, which is 7.1.0, but when I run cordova platform remove android and then cordova platform add android@7.1.0 I get this error 

Failed to install 'cordova-android-support-gradle-release': Error: ENOENT: no such file or directory, open '/Users/abdu/Downloads/deltasecurity/platforms/android/AndroidManifest.xml'

**Expected behavior:**

When I run cordova platform remove android then cordova platform add android@7.1.0 the operation should finish without errors

**Steps to reproduce:**

Try to remove android platform then add android platform 7.1.0

**Environment information**

- Cordova CLI version 
	- 8.0.0
- Cordova platform version
	-  android 7.1.0
        - ios 4.5.4
- Plugins & versions installed in project (including this plugin)
    - om.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
    - cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
    - cordova-plugin-console 1.0.1 "Console"
    - cordova-plugin-device 1.0.1 "Device"
    - cordova-plugin-dialogs 1.1.1 "Notification"
    - cordova-plugin-file 3.0.0 "File"
    - cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
    - cordova-plugin-network-information 1.0.1 "Network Information"
    - cordova-plugin-splashscreen 2.1.0 "Splashscreen"
    - cordova-plugin-statusbar 1.0.1 "StatusBar"
    - cordova-plugin-whitelist 1.0.0 "Whitelist"
    - cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
    - cordova.custom.plugins.exitapp 1.0.0 "ExitApp"
    - es6-promise-plugin 4.2.2 "Promise" 
    - nl.x-services.plugins.socialsharing 5.0.6 "SocialSharing"
- Dev machine OS and version, e.g.
    - OSX
        - ProductName:	Mac OS X
       - ProductVersion:	10.12.6
       - BuildVersion:	16G1314  

_Android build issue:_	
- Node JS version
    - v8.11.1
- Gradle version
	- `ls platforms/android/.gradle` not found at this path
        - `gradle -v` 4.7
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml` (file missing)
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'` (command not found)
	

**Console output**

<details>
<summary>console output</summary>

```

Using cordova-fetch for cordova-android@7.1.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: fr.delta2s.mitesis
	Name: Itesis
	Activity: MainActivity
	Android target: android-27
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.1.0
Android Studio project detected
Android Studio project detected
Installing "com.phonegap.plugins.PushPlugin" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-android-support-gradle-release" for android
Failed to install 'cordova-android-support-gradle-release': Error: ENOENT: no such file or directory, open '/Users/abdu/Downloads/deltasecurity/platforms/android/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (/Users/abdu/Downloads/deltasecurity/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/Users/abdu/Downloads/deltasecurity/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/abdu/Downloads/deltasecurity/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/Users/abdu/Downloads/deltasecurity/platforms/android/cordova/Api.js:223:57)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:47898) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/abdu/Downloads/deltasecurity/platforms/android/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (/Users/abdu/Downloads/deltasecurity/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/Users/abdu/Downloads/deltasecurity/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/abdu/Downloads/deltasecurity/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/Users/abdu/Downloads/deltasecurity/platforms/android/cordova/Api.js:223:57)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:47898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:47898) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

</details><br/><br/>

**Comment by dpa99c** [comment]
I tested the outlined scenario in my dev env, and it succeeded without the error (see console output below).

From the stack trace, the cause of this error looks to be in the `cordova-android` scripts, not caused by this plugin.

The reason for failure was:

	Failed to install 'cordova-android-support-gradle-release': Error: ENOENT: no such file or directory, open '/Users/abdu/Downloads/deltasecurity/platforms/android/AndroidManifest.xml'

This plugin makes no explicit reference to `AndroidManifest.xml`, either in its [plugin.xml](https://github.com/dpa99c/cordova-android-support-gradle-release/blob/master/plugin.xml) or [hook script](https://github.com/dpa99c/cordova-android-support-gradle-release/blob/master/scripts/apply-changes.js) since it is solely concerned with modifying Gradle configuration files.

The error message indicates the script is trying to access `platforms/android/AndroidManifest.xml`, which is the `cordova-android@6` location, but since the platform has been updated to `cordova-android@7`, the location of `AndroidManifest.html` has moved to `platforms/android/app/AndroidManifest.xml`.

I would hazard a guess that for some reason, some of the cordova modules in your `node_modules` directory (e.g. `cordova-lib`) have not been updated when upgrading to `cordova-android@7`, so are trying to reach the `AndroidManifest.xml` in its old `cordova-android@6` location. You should be able to confirm this if doing `rm -Rf node_modules && npm install` then fixes the error when removing/re-adding the platform.

<details>
<summary>console output</summary>

```


$ node -v
v8.11.1

$ cordova -v
8.0.0

$ cordova create test2 && cd test2
Creating a new cordova project.


$ cordova platform add android@6
Using cordova-fetch for cordova-android@6
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.4.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving android@~6.4.0 into config.xml file ...


$ cordova plugin add cordova-android-support-gradle-release
Installing "cordova-android-support-gradle-release" for android
Subproject Path: CordovaLib
cordova-android-support-gradle-release: Android platform: cordova-android@6
cordova-android-support-gradle-release: No custom version found in config.xml - using plugin default
Adding cordova-android-support-gradle-release to package.json
Saved plugin info for "cordova-android-support-gradle-release" to config.xml

$ cordova prepare android
cordova-android-support-gradle-release: Android platform: cordova-android@6
cordova-android-support-gradle-release: Wrote custom version '27.+' to D:\Temp\test2\platforms\android\build.gradle
cordova-android-support-gradle-release: Wrote custom version '27.+' to D:\Temp\test2\platforms\android\cordova-android-support-gradle-release\properties.gradle

$ cordova platform rm android && cordova platform add android@latest
Removing platform android from config.xml file...
Removing android from cordova.platforms array in package.json
Using cordova-fetch for cordova-android@latest
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-27
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.1.0
Android Studio project detected
Android Studio project detected
Installing "cordova-android-support-gradle-release" for android
Subproject Path: CordovaLib
Subproject Path: app
cordova-android-support-gradle-release: Android platform: cordova-android@7
cordova-android-support-gradle-release: Wrote custom version '27.+' to D:\Temp\test2\platforms\android\app\build.gradle
cordova-android-support-gradle-release: Wrote custom version '27.+' to D:\Temp\test2\platforms\android\app\cordova-android-support-gradle-release\properties.gradle
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

cordova-android-support-gradle-release: Android platform: cordova-android@7
cordova-android-support-gradle-release: Wrote custom version '27.+' to D:\Temp\test2\platforms\android\app\build.gradle
cordova-android-support-gradle-release: Wrote custom version '27.+' to D:\Temp\test2\platforms\android\app\cordova-android-support-gradle-release\properties.gradle
--save flag or autosave detected
Saving android@latest into config.xml file ...

$ cordova prepare android
Android Studio project detected
cordova-android-support-gradle-release: Android platform: cordova-android@7
cordova-android-support-gradle-release: Wrote custom version '27.+' to D:\Temp\test2\platforms\android\app\build.gradle
cordova-android-support-gradle-release: Wrote custom version '27.+' to D:\Temp\test2\platforms\android\app\cordova-android-support-gradle-release\properties.gradle

```

</details>

**Comment by abdurahmanadilovic** [comment]
Thanks for the quick reply, I will try to upgrade all plugins first before attempting to run cordova build. I will close this issue since it is not related to this plugin

**Comment by HugoHeneault** [comment]
🎉 For anyone having the same kind of issues I fixed it by adding an hook to my config.xml file as said here: https://gist.github.com/joeljeske/68121fa6d643e0937f50458d0172e16e
