### ISSUE TITLE
Got this error while build the app

### ISSUE THREAD

**Issue by alonetech** [dpa99c/cordova-android-support-gradle-release#25]
cordova -v  8.0.0
ionic 3
i just update cordova-android from 6.3.0 to 7.0.0 and remove platform and then add it again.
getting these error while build the app.

cordova-android-play-services-gradle-release: Android platform: cordova-android@7
cordova-android-play-services-gradle-release: No custom version found in config.xml - using plugin default
(node:5432) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Invalid data, chunk must be a string or buffer, not object

**Comment by dpa99c** [comment]
The above output in no indication that this plugin is responsible for the `UnhandledPromiseRejectionWarning`, it  just indicates that this plugin's [log statement](https://github.com/dpa99c/cordova-android-support-gradle-release/blob/master/scripts/apply-changes.js#L70) was the last to appear before the error occurred.

I suggest adding the platform using the `--verbose` flag to get more detailed output which should indicate where the error is occurring:

    cordova platform add android@7.0.0 --verbose

**Comment by dpa99c** [comment]
Closed due to no response from OP
