### ISSUE TITLE
Android build fails on cordova-android 7.1.2

### ISSUE THREAD

**Issue by dmitryevseev** [dpa99c/cordova-android-support-gradle-release#31]
**I'm submitting a ...**  (check one with "x"):

- [x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

Initializing gradle wrapper fails on latest [cordova-android 7.1.2](https://cordova.apache.org/announcements/2018/11/07/cordova-android-7.1.2.html).

After running cordova prepare, I'm creating a graddle wrapper with:

    gradle wrapper --gradle-version 4.4 --distribution-type all

The output is:

```
$ gradle wrapper --gradle-version 4.4 --distribution-type all
> Configure project :app
 Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.
FAILURE: Build failed with an exception.
* Where:
Script '.../cordova/platforms/android/cordova-android-play-services-gradle-release/mobile-cordova-android-play-services-gradle-release.gradle' line: 11
* What went wrong:
A problem occurred evaluating script.
> Could not read script '.../cordova/platforms/android/app/cordova-android-play-services-gradle-release/properties.gradle' as it does not exist.
```

**Expected behavior:**

The gradle wrapper is created. This issue can't be reproduced with cordova-android 7.1.1.

**Steps to reproduce:**

Specify version or cordova-android in config.xml:

   <engine name="android" spec="=7.1.2" />

Then run prepare:

    cordova prepare --verbose

After go to platforms/android directory and run:

    gradle wrapper --gradle-version 4.4 --distribution-type all

**Environment information**

- Cordova CLI version 8.0.0
- Cordova platform version

    Installed platforms:
      android 7.1.2

- Plugins & versions installed in project (including this plugin)

```
cordova-android-play-services-gradle-release 1.4.4 "cordova-android-play-services-gradle-release"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-privacyscreen 0.4.3 "PrivacyScreenPlugin"
cordova-plugin-recaptcha 1.0.2 "Cordova Recaptcha"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-secure-storage 3.0.0 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-translucent-statusbar 1.0.0 "Translucent Statusbar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.2.3 "PushPlugin"
```

- Dev machine OS
    - OSX 10.13.6
        
_Android build issue:_	
- Node JS version v8.11.1
- Gradle version 4.10.2 vcs-1
- Target Android SDK version 27

**Other information:**

From cordova changelog it looks related to this issue: https://issues.apache.org/jira/browse/CB-14125

Find release notes here: https://cordova.apache.org/announcements/2018/11/07/cordova-android-7.1.2.html

**Comment by dpa99c** [comment]
CB-14125 title should be changed to "**Decrease** cordova-android old plugin compatibility" 😞

I'll take a look when I get a minute .
