### ISSUE TITLE
Plugin cannot find config.xml when it is located in www folder

### ISSUE THREAD

**Issue by henkkelder** [dpa99c/cordova-android-support-gradle-release#33]
As the tittle says. 
Since I also use phonegap build my config.xml must be located in the www folder.

**Comment by dpa99c** [comment]
This plugin [relies on hook scripts](https://github.com/dpa99c/cordova-android-support-gradle-release/blob/master/plugin.xml#L17) which are [not supported by Phonegap Build](https://github.com/phonegap/build/issues/425) so it will not work.

**Comment by henkkelder** [comment]
Thats not my point. Its just the location of config.xml where the plugin fails when using with the CLI. 

Officially Cordova supports to have the config.sys in the project folder or in de www folder. Your plugin lacks support for the latter.

I build android locally on my own pc, but IOS using PGB.
 Since PGB wants the plugin in the www folder I must have it there. 
But then my local builds give errors when I include your plugin.

**Comment by dpa99c** [comment]
OK, I misunderstood. 
It should be possible to detect the location of `config.xml` in the hook scripts.
