### ISSUE TITLE
Dependant lib semver version is too old, is there a plan for upgrade ?

### ISSUE THREAD

**Issue by modimoni** [dpa99c/cordova-android-support-gradle-release#35]
I see that semver version used ( dependancy)  is 5.1.0 which is from Nov 2015. Do you have any plan to upgrade to 5.6.0 from Oct 2018

Thanks
Modi

**Comment by dpa99c** [comment]
What would be the advantage of upgrading to v5.6.0?
Looking at the [`semver` CHANGELOG](https://github.com/npm/node-semver/blob/master/CHANGELOG.md), the versions between 5.2 and 5.6 only add new features which this plugin does not make use of.

**Comment by dpa99c** [comment]
Closed due to no response
