### ISSUE TITLE
Cordova 9 EXCEPTION: No plugins found. Run 'cordova plugin save' in order to save your plugins to your config.xml-file

### ISSUE THREAD

**Issue by DavidWiesner** [dpa99c/cordova-android-support-gradle-release#38]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report
**Current behavior:**
If I add your plugin to a existing cordova 9 project I got the following error:
`EXCEPTION: No plugins found. Run 'cordova plugin save' in order to save your plugins to your config.xml-file`.

Cordova 9 do not require to add the plugin to the config.xml. But you parsing the config.xml 

**Expected behavior:**
For cordova 9 parse the package.json to get the 'ANDROID_SUPPORT_VERSION' variable.

**Steps to reproduce:**
- remove all platforms in a project
- remove your plugin in config.xml by hand
- add platform e.g.: android again with `cordova platform add`

**Environment information**
```
cordova -v
9.0.0 (cordova-lib@9.0.1)
Installed platforms:
  android 8.0.0
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0

cordova-android-play-services-gradle-release 2.1.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 2.1.0 "cordova-android-support-gradle-release"
es6-promise-plugin 4.2.2 "Promise"

Mac OSX mojave
```

**Comment by dpa99c** [comment]
Published to npm in v3.0.0
