### ISSUE TITLE
Not compatible with cordova 9

### ISSUE THREAD

**Issue by lovelyelfpop** [dpa99c/cordova-android-support-gradle-release#39]
Using "requireCordovaModule" to load non-cordova module "xxx" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by tuananh1998hust** [comment]
i have same err ? how i can fix it ?

**Comment by dayaki** [comment]
@lovelyelfpop @tuananh1998hust  how were you able to solve this?

**Comment by lovelyelfpop** [comment]
@dayaki The lastest version solved this issue
