### ISSUE TITLE
build failed with jenkins server

### ISSUE THREAD

**Issue by danielehrhardt** [dpa99c/cordova-android-support-gradle-release#4]
Hi

i want to use your plugin with a jenkins build server.
All is furnished and the build is running one time
the second the the build fails
becuase in the background is running a java.exe i think it is the gradle demon
This is the Error message.
![image](https://user-images.githubusercontent.com/19570043/30396018-7209e608-98c8-11e7-9742-138b6e24a5b1.png)
Do you have an idear how to fix it?

Thanks,
Daniel

**Comment by dpa99c** [comment]
This is a Gradle build bug on the Windows platform and as such this plugin has no control on how Gradle functions internally

**Comment by danielehrhardt** [comment]
yes to fix this stop the gradle deamon at the end of the Build.
gradle.exe --stop

It is important that you use the gradle from the build Folder
