### ISSUE TITLE
Windows Build Permission Error 

### ISSUE THREAD

**Issue by danielehrhardt** [dpa99c/cordova-android-support-gradle-release#5]
Hi,

i love your Plugin and it is working good but i have one Problem on Windows PCs. I can reproduce this Bug on different Windows PCs.

When i add this Plugin and run cordova build android
i get the following Issue:
![image](https://user-images.githubusercontent.com/19570043/30961159-999150f2-a445-11e7-98d9-ec28dcc05823.png)

i found out that the android-sdk folder have now the wrong permission. So the command cannot write files there. 

When i change the folder permissions recursive to Everyone or the User it is working. 

Can you please check this Bug?

Thank You
Daniel

**Comment by dpa99c** [comment]
How does this issue have any relation to this plugin? It's not like this plugin can control the file permissions on the installed Android SDK...
