### ISSUE TITLE
conflict with com.android.support:multidex

### ISSUE THREAD

**Issue by yxliang01** [dpa99c/cordova-android-support-gradle-release#8]
`com.android.support:multidex` doesn't use the version other ones in `com.android.support` uses. Therefore, when you specify `ANDROID_SUPPORT_VERSION` to say `26.+`, it will try to use `com.android.support:multidex:26.+` which doesn't exist as the available version of `com.android.support:multidex` are `1.0.0`, `1.0.1`, `1.0.2` at the moment.

Thanks!

**Comment by Gurrt** [comment]
@yxliang01 I also ran into this problem I made https://github.com/dpa99c/cordova-android-support-gradle-release/pull/9 as a fix for this.

**Comment by yxliang01** [comment]
@Gurrt Yeah #9 fixes! Thanks a lot! :)

**Comment by dpa99c** [comment]
@Gurrt Thanks for the fix, it's now published to npm in version 1.1.2
